ARG IMAGE_VARIANT=slim-bullseye
ARG PYTHON_VERSION=3.9
ARG PYSPARK_VERSION=3.5.7

FROM python:${PYTHON_VERSION}-${IMAGE_VARIANT}

RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-11-jre-headless && \
    rm -rf /var/lib/apt/lists/*

RUN pip --no-cache-dir install pyspark==3.5.7

COPY . .
CMD ["python", "main.py"]